<?php

namespace App\DTO;

class ProductData
{
    public function __construct(
        public readonly ?string $name,
        public readonly ?string $slug,
        public readonly ?float $price,
        public readonly ?float $sale_price,
        public readonly ?float $max_price,
        public readonly ?float $min_price,
        public readonly ?int $type_id,
        public readonly ?int $shop_id,
        public readonly ?int $author_id,
        public readonly ?int $manufacturer_id,
        public readonly ?string $language,
        public readonly ?string $product_type,
        public readonly ?int $quantity,
        public readonly ?string $unit,
        public readonly ?bool $is_digital,
        public readonly ?bool $is_external,
        public readonly ?string $external_product_url,
        public readonly ?string $external_product_button_text,
        public readonly ?string $description,
        public readonly ?string $sku,
        public readonly ?array $image,
        public readonly ?array $gallery,
        public readonly ?array $video,
        public readonly ?string $status,
        public readonly ?string $height,
        public readonly ?string $length,
        public readonly ?string $width,
        public readonly ?bool $in_stock,
        public readonly ?bool $is_taxable,
        public readonly ?int $sold_quantity,
        public readonly ?string $visibility,
        public readonly ?array $categories,
        public readonly ?array $tags,
        public readonly ?array $dropoff_locations,
        public readonly ?array $pickup_locations,
        public readonly ?array $persons,
        public readonly ?array $features,
        public readonly ?array $deposits,
        public readonly ?array $metas,
        public readonly ?array $variations,
        public readonly ?array $variation_options,
        public readonly ?array $digital_file,
        public readonly ?bool $inform_purchased_customer,
        public readonly ?string $product_update_message,
        public readonly ?bool $is_rental,
    ) {}

    public static function fromRequest(array $data): self
    {
        return new self(
            name: $data['name'] ?? null,
            slug: $data['slug'] ?? null,
            price: isset($data['price']) ? (float) $data['price'] : null,
            sale_price: isset($data['sale_price']) ? (float) $data['sale_price'] : null,
            max_price: isset($data['max_price']) ? (float) $data['max_price'] : null,
            min_price: isset($data['min_price']) ? (float) $data['min_price'] : null,
            type_id: $data['type_id'] ?? null,
            shop_id: $data['shop_id'] ?? null,
            author_id: $data['author_id'] ?? null,
            manufacturer_id: $data['manufacturer_id'] ?? null,
            language: $data['language'] ?? config('shop.default_language', 'id'),
            product_type: $data['product_type'] ?? null,
            quantity: $data['quantity'] ?? null,
            unit: $data['unit'] ?? null,
            is_digital: isset($data['is_digital']) ? (bool) $data['is_digital'] : null,
            is_external: isset($data['is_external']) ? (bool) $data['is_external'] : null,
            external_product_url: $data['external_product_url'] ?? null,
            external_product_button_text: $data['external_product_button_text'] ?? null,
            description: $data['description'] ?? null,
            sku: $data['sku'] ?? null,
            image: $data['image'] ?? null,
            gallery: $data['gallery'] ?? null,
            video: $data['video'] ?? null,
            status: $data['status'] ?? null,
            height: $data['height'] ?? null,
            length: $data['length'] ?? null,
            width: $data['width'] ?? null,
            in_stock: isset($data['in_stock']) ? (bool) $data['in_stock'] : null,
            is_taxable: isset($data['is_taxable']) ? (bool) $data['is_taxable'] : null,
            sold_quantity: $data['sold_quantity'] ?? 0,
            visibility: $data['visibility'] ?? 'visible',
            categories: $data['categories'] ?? null,
            tags: $data['tags'] ?? null,
            dropoff_locations: $data['dropoff_locations'] ?? null,
            pickup_locations: $data['pickup_locations'] ?? null,
            persons: $data['persons'] ?? null,
            features: $data['features'] ?? null,
            deposits: $data['deposits'] ?? null,
            metas: $data['metas'] ?? null,
            variations: $data['variations'] ?? null,
            variation_options: $data['variation_options'] ?? null,
            digital_file: $data['digital_file'] ?? null,
            inform_purchased_customer: (bool) ($data['inform_purchased_customer'] ?? false),
            product_update_message: $data['product_update_message'] ?? null,
            is_rental: isset($data['is_rental']) ? (bool) $data['is_rental'] : null,
        );
    }
}
